version: "2.2"
services:
  docker_workstation_computer:
    build:
      context: ..
      dockerfile: workstation_computer/Dockerfile
    container_name: workstation_computer_docker
    tty: true
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856
    network_mode: host
    volumes:
      - ../../calibration:/root/git/calibration

